apiVersion: v1
kind: Service
metadata:
  name: medscribe-gateway
  namespace: medscribe
  labels:
    app.kubernetes.io/name: medscribe-gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: medscribe-gateway
  ports:
    - name: http
      port: 80
      targetPort: http
